// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { evoCrmBlock } from ".";
import { auth } from "./auth";

export const evoCrmBlockSchema = parseBlockSchema(evoCrmBlock);
export const evoCrmCredentialsSchema = parseBlockCredentials(
  evoCrmBlock.id,
  auth,
);
